<h1 style="text-align: center;">Ciencia de Datos en Turismo
</h3>
<h3 style="text-align: center;"> Práctica 1b </h3>
<h3 style="text-align: center;"> Octubre 2026 </h3>

## Ejercicio 1

En el siguiente enlace se encuentran dos bases de datos: [Madrid att.csv](https://ulpgc-my.sharepoint.com/:x:/g/personal/juan_hernandez_ulpgc_es/IQCDwsvwAJHMTbjj6aWjT9cSAUH8E38DSryiL7VJaYWaNTQ?e=JPji0A) y [Madrid reviews.csv](https://ulpgc-my.sharepoint.com/:x:/g/personal/juan_hernandez_ulpgc_es/IQDlTCH5csHrQqvs-B9R423_AbelpaiTngxoLEZ1FMEFt9s?e=Miwnb3). 

- La base de datos **Madrid att.csv** contiene 673 atracciones de Madrid con su identificador (id atr), número de revisiones recibidas, dirección, posición en una lista ordenada de atracciones en Madrid y categorías de atracciones que la identifican (tags).

- La base de datos **Madrid reviews.csv** contiene 125674 revisiones de las atracciones de Madrid incluyendo el ID del revisor y atracción (id atr), rating de la atracción (en valores enteros del 1 al 5), fecha de la revisión (entre 2006 y 2018) y otra información que identifica al revisor.

Se quieren determinar los factores que influyen en el rating obtenido. Dicho de otra manera, el objetivo es ajustar lo mejor posible la siguiente función f:

$$ f(x_{i1}, x_{i2}, ..., x_{id}) = r_i \quad \forall i \in \{1, 2, ..., n\} $$

siendo $ r_i $ el rating de la atracción $ i $-ésima y $ x_{ij} $ las variables explicativas del modelo. El trabajo a realizar es el siguiente:

**(a)**	Determinación de la variable target y las explicativas.

In [5]:
import pandas as pd
import csv

# 1. Cargar los datos indicando a pandas que ignore las comillas conflictivas
df_att = pd.read_csv('Madrid_att(in).csv', sep=';', quoting=csv.QUOTE_NONE)
df_reviews = pd.read_csv('Madrid_reviews(in).csv', sep=';', quoting=csv.QUOTE_NONE)

# 2. Limpiar las comillas (") y las comas sueltas (,) que traían los archivos por error
# Limpiamos las atracciones
df_att = df_att.replace('"', '', regex=True).replace(',+$', '', regex=True)
df_att.columns = df_att.columns.str.replace('"', '').str.replace(',+$', '', regex=True)

# Limpiamos las revisiones
df_reviews = df_reviews.replace('"', '', regex=True).replace(',+$', '', regex=True)
df_reviews.columns = df_reviews.columns.str.replace('"', '').str.replace(',+$', '', regex=True)

# Visualizar las bases ya limpias y correctamente estructuradas
display(df_att.head(10))
display(df_reviews.head(10))

,,id_atr,nombre_atr,num_rev_atr,address,pos,tags
0,1,d191050,Retiro Park (Parque del Retiro),47778,Between C. Alfonso XII and Avenida de Menendez...,#1 of 811 things to do in Madrid,"Nature & Parks, Sights & Landmarks, Bodies of ..."
1,2,d190143,Prado National Museum,49908,"Calle Ruiz de Alarcon 23, 28014 Madrid, Spain",#2 of 811 things to do in Madrid,"Museums, Specialty Museums"
2,3,d198867,Museo Nacional Thyssen-Bornemisza,14687,"Paseo Prado 8, 28048 Madrid, Spain",#3 of 811 things to do in Madrid,"Museums, Specialty Museums"
3,4,d796251,Stadio Santiago Bernabeu,19879,"Avenida de Concha Espina 1 | Bernabeu Stadium,...",#4 of 811 things to do in Madrid,"Sights & Landmarks, Arenas & Stadiums"
4,5,d190146,Royal Palace of Madrid,30186,"Calle Bailen, 28071 Madrid, Spain",#5 of 811 things to do in Madrid,"Museums, Sights & Landmarks, Art Museums, Hist..."
5,6,d190152,Museo Nacional Centro de Arte Reina Sofia,14324,"Calle de Santa Isabel 52, 28012 Madrid, Spain",#6 of 811 things to do in Madrid,"Museums, Art Museums"
6,7,d246516,Gran Via,11729,"Street Gran Via, 28013 Madrid, Spain",#7 of 811 things to do in Madrid,"Sights & Landmarks, Points of Interest & Landm..."
7,8,d244303,Templo de Debod,11672,"Calle Ferraz 1, 28008 Madrid, Spain",#8 of 811 things to do in Madrid,"Sights & Landmarks, Historic Sites"
8,9,d190142,Plaza Mayor,22546,"Calle Gerona 4, 28012 Madrid, Spain",#9 of 811 things to do in Madrid,"Sights & Landmarks, Points of Interest & Landm..."
9,10,d1520183,Mercado San Miguel,26781,"Plaza San Miguel, 28005 Madrid, Spain",#10 of 811 things to do in Madrid,"Shopping, Flea & Street Markets"

,,user_id,id_atr,rating_rev,date_rev,leng,usr.name,usr.login,since,hometown,info.usr,tag.usr
0,1,1E4BA1FBFB6D49508A381F5E78E633F1,d592827,5,2017-10-11,en,mercedes n,mercedesn,TripAdvisor member since 2011,"From Catalonia, Spain","135 Contributions, 40 Cities visited, 23 Helpf...","Art and Architecture Lover, Foodie, Urban Expl..."
1,2,FC1C559F644A6D700CAAC522B0027DA1,d592827,4,2017-08-24,en,Miriam67,Miriam67,TripAdvisor member since 2008,"50-64 woman from Malaga, Spain","48 Contributions, 273 Cities visited, 13 Helpf...","Art and Architecture Lover, Foodie, History Buff"
2,3,F32F65328FB68C92FF7D94BDE3D37CC5,d592827,5,2017-08-16,en,Monicalventura,Monicalventura,TripAdvisor member since 2014,From San francisco,"37 Contributions, 12 Cities visited, 8 Helpful...",NA
3,4,00925F3454F45A577B17C20C400F3540,d592827,5,2017-07-07,en,Kit M,413kitm,TripAdvisor member since 2014,NaN,"18 Contributions, 7 Cities visited, 1 Helpful ...",NA
4,5,83462D5B5273D9952C78D50C0F48528D,d592827,5,2017-06-24,en,521alberth,521alberth,TripAdvisor member since 2013,NaN,"48 Contributions, 193 Cities visited, 14 Helpf...","Art and Architecture Lover, Foodie, Urban Expl..."
5,6,8DC7D0CDD85BAD91F37DCBFC9E03B9C6,d592827,5,2017-05-21,en,RichNY1,RichNY1,TripAdvisor member since 2006,"From New York City, New York","84 Contributions, 130 Cities visited, 75 Helpf...","Urban Explorer, Like a Local, History Buff, 60..."
6,7,E323632A70618B68366FEF04BBDDDCB9,d592827,4,2017-04-13,en,Cristobal P,768cristobalp,TripAdvisor member since 2014,"50-64 man from Santiago, Chile","22 Contributions, 346 Cities visited, 11 Helpf...","Foodie, Urban Explorer, Nature Lover, 60+ Trav..."
7,8,4FF815E08B67B5FE918EDB965CEA41EB,d592827,4,2017-01-08,en,MataHari2013,MataHari2013,TripAdvisor member since 2013,"From Wiesbaden, Hessen, Germany","27 Contributions, 231 Cities visited, 11 Helpf...","Art and Architecture Lover, Vegetarian, Foodie..."
8,9,7A1D2FF3EF6E4DC0C648FE6C0FF24B6F,d592827,5,2016-11-23,en,Carlos B,393CarlosB,TripAdvisor member since 2013,"From Jersey City, New Jersey","24 Contributions, 10 Cities visited, 9 Helpful...","Shopping Fanatic, Peace and Quiet Seeker, Luxu..."
9,10,58CE37A49BD1E83AF02F090F0D41FFD0,d592827,4,2016-11-02,en,nmartinmarcus25,nmartinmarcus25,TripAdvisor member since 2016,"50-64 woman from Garrucha, Spain","8 Contributions, 2 Cities visited",NA

In [7]:
import pandas as pd
import csv
import re
import time
from geopy.geocoders import Nominatim
from geopy.exc import GeocoderTimedOut

# Asumimos que df_att ya está cargado en este punto...

# 1. Aseguramos que la columna existe (si no, la crea vacía)
if 'codigo_postal' not in df_att.columns:
    df_att['codigo_postal'] = None

# 2. Extraer CP con Regex SOLO en las filas donde falte (para no pisar datos guardados)
mask_nulos = df_att['codigo_postal'].isna()
df_att.loc[mask_nulos, 'codigo_postal'] = df_att.loc[mask_nulos, 'address'].str.extract(r'\b(28\d{3})\b')[0]

faltantes_iniciales = df_att['codigo_postal'].isna().sum()
print(f"Códigos postales extraídos con Regex/Guardados. Faltan por rellenar: {faltantes_iniciales}")

# 3. Rellenar usando Geopy con doble intento
geolocator = Nominatim(user_agent="turismo_madrid_ds_project")

def obtener_cp_desde_texto(texto):
    """Función genérica para buscar en OpenStreetMap a partir de cualquier texto"""
    if pd.isna(texto):
        return None
    try:
        texto_limpio = str(texto).split('|')[0].strip()
        location = geolocator.geocode(texto_limpio, addressdetails=True, timeout=10)
        
        if location and 'address' in location.raw:
            cp = location.raw['address'].get('postcode')
            if cp:
                # Validar que empiece por 28 y tenga 5 dígitos, por seguridad
                match = re.search(r'\b(28\d{3})\b', str(cp))
                if match:
                    return match.group(1)
    except Exception:
        pass # Ignorar errores de conexión
    return None

# Filtramos estrictamente las que NO tienen código postal tras el regex
filas_sin_cp = df_att[df_att['codigo_postal'].isna()]

print("Iniciando búsqueda online (dirección y nombre)...")

for index, row in filas_sin_cp.iterrows():
    # INTENTO 1: Buscar por la dirección
    nuevo_cp = obtener_cp_desde_texto(row['address'])
    time.sleep(1) # Pausa obligatoria de la API
    
    # INTENTO 2: Si falla la dirección, buscar por el nombre de la atracción
    if not nuevo_cp:
        # Le añadimos ", Madrid" para que el mapa sepa dónde buscar
        busqueda_por_nombre = str(row['nombre_atr']) + ", Madrid"
        nuevo_cp = obtener_cp_desde_texto(busqueda_por_nombre)
        time.sleep(1) # Pausa obligatoria tras el segundo intento
        
    # Si cualquiera de los dos intentos funcionó, lo guardamos
    if nuevo_cp:
        df_att.at[index, 'codigo_postal'] = nuevo_cp

# Revisamos el resultado final
faltantes_finales = df_att['codigo_postal'].isna().sum()
print(f"\nProceso terminado. Códigos postales faltantes ahora: {faltantes_finales}")

# Mostrar una muestra de resultados
display(df_att[['nombre_atr', 'address', 'codigo_postal']].head(10))

Códigos postales extraídos con Regex/Guardados. Faltan por rellenar: 163
Iniciando búsqueda online (dirección y nombre)...

Proceso terminado. Códigos postales faltantes ahora: 46

,nombre_atr,address,codigo_postal
0,Retiro Park (Parque del Retiro),Between C. Alfonso XII and Avenida de Menendez...,28010
1,Prado National Museum,"Calle Ruiz de Alarcon 23, 28014 Madrid, Spain",28014
2,Museo Nacional Thyssen-Bornemisza,"Paseo Prado 8, 28048 Madrid, Spain",28048
3,Stadio Santiago Bernabeu,"Avenida de Concha Espina 1 | Bernabeu Stadium,...",28036
4,Royal Palace of Madrid,"Calle Bailen, 28071 Madrid, Spain",28071
5,Museo Nacional Centro de Arte Reina Sofia,"Calle de Santa Isabel 52, 28012 Madrid, Spain",28012
6,Gran Via,"Street Gran Via, 28013 Madrid, Spain",28013
7,Templo de Debod,"Calle Ferraz 1, 28008 Madrid, Spain",28008
8,Plaza Mayor,"Calle Gerona 4, 28012 Madrid, Spain",28012
9,Mercado San Miguel,"Plaza San Miguel, 28005 Madrid, Spain",28005

In [8]:
# Extraer los números de cada categoría utilizando expresiones regulares
df_reviews['Contributions'] = df_reviews['info.usr'].str.extract(r'(\d+)\s*Contribution').astype(float)
df_reviews['Cities_visited'] = df_reviews['info.usr'].str.extract(r'(\d+)\s*Cit').astype(float)
df_reviews['Helpful_votes'] = df_reviews['info.usr'].str.extract(r'(\d+)\s*Helpful').astype(float)
df_reviews['Photos'] = df_reviews['info.usr'].str.extract(r'(\d+)\s*Photo').astype(float)

# Rellenar los valores nulos (NaN) con 0 en todas las nuevas columnas, tal como indicaste para las fotos
cols_info = ['Contributions', 'Cities_visited', 'Helpful_votes', 'Photos']
df_reviews[cols_info] = df_reviews[cols_info].fillna(0).astype(int)

# Opcional: Eliminar la columna original de texto ya que la información ha sido extraída
df_reviews = df_reviews.drop(columns=['info.usr'])

# Visualizar el resultado
display(df_reviews[['user_id'] + cols_info].head())

,user_id,Contributions,Cities_visited,Helpful_votes,Photos
0,1E4BA1FBFB6D49508A381F5E78E633F1,135,40,23,35
1,FC1C559F644A6D700CAAC522B0027DA1,48,273,13,1
2,F32F65328FB68C92FF7D94BDE3D37CC5,37,12,8,0
3,00925F3454F45A577B17C20C400F3540,18,7,1,0
4,83462D5B5273D9952C78D50C0F48528D,48,193,14,58

In [15]:
# Extraemos los dígitos que van justo después del símbolo '#'
df_att['pos'] = df_att['pos'].str.extract(r'#(\d+)').astype(int)

# Visualizamos para comprobar el cambio
display(df_att[['nombre_atr', 'pos']].head(15))

                                   nombre_atr  pos
0             Retiro Park (Parque del Retiro)    1
1                       Prado National Museum    2
2           Museo Nacional Thyssen-Bornemisza    3
3                    Stadio Santiago Bernabeu    4
4                      Royal Palace of Madrid    5
5   Museo Nacional Centro de Arte Reina Sofia    6
6                                    Gran Via    7
7                             Templo de Debod    8
8                                 Plaza Mayor    9
9                          Mercado San Miguel   10
10                              Museo Sorolla   11
11                Museo Arqueologico Nacional   12
12                             Museo Cerralbo   13
13                      Parque de El Capricho   14
14     Iglesia de San Antonio de Los Alemanes   15

In [22]:
# Cuenta cuántas celdas en 'since' empiezan por 'TripAdvisor member'
cantidad = df_reviews['since'].str.startswith('TripAdvisor member').sum()
print(f"Empiezan por TripAdvisor member: {cantidad}")

Empiezan por TripAdvisor member: 125764

In [24]:
# Extraemos solo los 4 dígitos del año y lo convertimos a número
df_reviews['since_year'] = df_reviews['since'].str.extract(r'(\d{4})').astype(int)

# Si quieres ver cómo queda:
display(df_reviews[['since', 'since_year']].head())

                           since  since_year
0  TripAdvisor member since 2011        2011
1  TripAdvisor member since 2008        2008
2  TripAdvisor member since 2014        2014
3  TripAdvisor member since 2014        2014
4  TripAdvisor member since 2013        2013

In [ ]:
# Lista de variables explicativas (features)
variables_explicativas = [
    'tags',          # Características de la atracción
    'pos',           # Ranking de la atracción
    'num_rev_atr',   # Popularidad de la atracción
    'tag.usr',       # Preferencias del usuario
    'Contributions', # Nivel de contribución del usuario
    'Cities_visited', # Nivel de experiencia del usuario
    'Helpful_votes', # Nivel de experiencia del usuario
    'Photos',        # Nivel de experiencia del usuario
    'address',       # Ubicación de la atracción
    'hometown',      # Origen del usuario
    'since_year',    # Antigüedad del usuario
    'leng',          # Idioma / Perfil cultural
    'date_rev'       # Contexto temporal (estacionalidad)
]

# Variable objetivo
variable_target = 'rating_rev'


**(b)**	Limpieza y análisis exploratorio de los datos. Se pueden realizar visualizaciones, test de hipótesis y clustering o aplicación de técnicas de reducción de la dimensionalidad.

**(c)**	Prueba con diversos métodos de clasificación.


**(d)**	Validar el método, esto es, analizar la fiabilidad del método.


**(e)**	Escribir conclusiones del estudio de acuerdo al objetivo de partida, esto es, analizar los factores que más influyen en el rating obtenido por la atracción.